// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/vc/types"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Repository
func (_mock *Repository) Create(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string) (*types.VerifiableCredential, error) {
	ret := _mock.Called(ctx, credential, resolverMetadataID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.VerifiableCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.VerifiableCredential, string) (*types.VerifiableCredential, error)); ok {
		return returnFunc(ctx, credential, resolverMetadataID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.VerifiableCredential, string) *types.VerifiableCredential); ok {
		r0 = returnFunc(ctx, credential, resolverMetadataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.VerifiableCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.VerifiableCredential, string) error); ok {
		r1 = returnFunc(ctx, credential, resolverMetadataID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *types.VerifiableCredential
//   - resolverMetadataID string
func (_e *Repository_Expecter) Create(ctx interface{}, credential interface{}, resolverMetadataID interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, credential, resolverMetadataID)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.VerifiableCredential
		if args[1] != nil {
			arg1 = args[1].(*types.VerifiableCredential)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_Create_Call) Return(verifiableCredential *types.VerifiableCredential, err error) *Repository_Create_Call {
	_c.Call.Return(verifiableCredential, err)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string) (*types.VerifiableCredential, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type Repository
func (_mock *Repository) GetByID(ctx context.Context, id string) (*types.VerifiableCredential, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *types.VerifiableCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.VerifiableCredential, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.VerifiableCredential); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.VerifiableCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetByID(ctx interface{}, id interface{}) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, id string)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(verifiableCredential *types.VerifiableCredential, err error) *Repository_GetByID_Call {
	_c.Call.Return(verifiableCredential, err)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*types.VerifiableCredential, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByResolverMetadata provides a mock function for the type Repository
func (_mock *Repository) GetByResolverMetadata(ctx context.Context, resolverMetadataID string) ([]*types.VerifiableCredential, error) {
	ret := _mock.Called(ctx, resolverMetadataID)

	if len(ret) == 0 {
		panic("no return value specified for GetByResolverMetadata")
	}

	var r0 []*types.VerifiableCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*types.VerifiableCredential, error)); ok {
		return returnFunc(ctx, resolverMetadataID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*types.VerifiableCredential); ok {
		r0 = returnFunc(ctx, resolverMetadataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.VerifiableCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, resolverMetadataID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetByResolverMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByResolverMetadata'
type Repository_GetByResolverMetadata_Call struct {
	*mock.Call
}

// GetByResolverMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - resolverMetadataID string
func (_e *Repository_Expecter) GetByResolverMetadata(ctx interface{}, resolverMetadataID interface{}) *Repository_GetByResolverMetadata_Call {
	return &Repository_GetByResolverMetadata_Call{Call: _e.mock.On("GetByResolverMetadata", ctx, resolverMetadataID)}
}

func (_c *Repository_GetByResolverMetadata_Call) Run(run func(ctx context.Context, resolverMetadataID string)) *Repository_GetByResolverMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetByResolverMetadata_Call) Return(verifiableCredentials []*types.VerifiableCredential, err error) *Repository_GetByResolverMetadata_Call {
	_c.Call.Return(verifiableCredentials, err)
	return _c
}

func (_c *Repository_GetByResolverMetadata_Call) RunAndReturn(run func(ctx context.Context, resolverMetadataID string) ([]*types.VerifiableCredential, error)) *Repository_GetByResolverMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository) Update(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string) (*types.VerifiableCredential, error) {
	ret := _mock.Called(ctx, credential, resolverMetadataID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *types.VerifiableCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.VerifiableCredential, string) (*types.VerifiableCredential, error)); ok {
		return returnFunc(ctx, credential, resolverMetadataID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.VerifiableCredential, string) *types.VerifiableCredential); ok {
		r0 = returnFunc(ctx, credential, resolverMetadataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.VerifiableCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.VerifiableCredential, string) error); ok {
		r1 = returnFunc(ctx, credential, resolverMetadataID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *types.VerifiableCredential
//   - resolverMetadataID string
func (_e *Repository_Expecter) Update(ctx interface{}, credential interface{}, resolverMetadataID interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, credential, resolverMetadataID)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.VerifiableCredential
		if args[1] != nil {
			arg1 = args[1].(*types.VerifiableCredential)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_Update_Call) Return(verifiableCredential *types.VerifiableCredential, err error) *Repository_Update_Call {
	_c.Call.Return(verifiableCredential, err)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(ctx context.Context, credential *types.VerifiableCredential, resolverMetadataID string) (*types.VerifiableCredential, error)) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}
