// Code generated by go-swagger; DO NOT EDIT.

package models

// V1alpha1RegisterIssuerResponse Returns a registration response for the issuer
//
// # Empty response
//
// swagger:model v1alpha1RegisterIssuerResponse
type V1alpha1RegisterIssuerResponse any
