# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: 2

project_name: identity
builds:
  # You can have multiple builds defined as a yaml list
  - #
    # ID of the build.
    #
    # Default: Project directory name.
    id: "issuer-cli"

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    #
    # Default: Project directory name.
    binary: identity

    # GOOS list to build for.
    # For more info refer to: https://pkg.go.dev/cmd/go#hdr-Environment_variables
    #
    # Default: [ 'darwin', 'linux', 'windows' ].
    goos:
      - darwin
      - linux
      - windows

    # GOARCH to build for.
    # For more info refer to: https://pkg.go.dev/cmd/go#hdr-Environment_variables
    #
    # Default: [ '386', 'amd64', 'arm64' ].
    goarch:
      - amd64
      - arm64

    ldflags:
      - "-X github.com/agntcy/identity/cmd/issuer/commands/version.Version={{.Version}}"
      - "-X github.com/agntcy/identity/cmd/issuer/commands/version.BuildDate={{.Date}}"
      - "-X github.com/agntcy/identity/cmd/issuer/commands/version.GitCommit={{.Commit}}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

binary_signs:
  - id: issuer-cli-sign
    signature: ${artifact}_{{ .Os }}_{{ .Arch }}_sig"
    cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--detach-sign"
      - "--armor"
      - "--output"
      - "${signature}"
      - "${artifact}"
    artifacts: binary
    ids:
      - issuer-cli
    env:
      - GPG_TTY=/dev/tty
    output: true