---
all: false
dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
filename: "{{.InterfaceName | snakecase}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/agntcy/identity/internal/node:
    interfaces:
      IdService: {}
      IssuerService: {}
      VerifiableCredentialService: {}
      IDGenerator: {}
  github.com/agntcy/identity/internal/core/id:
    interfaces:
      IdRepository: {}
  github.com/agntcy/identity/internal/core/issuer:
    interfaces:
      Repository: {}
  github.com/agntcy/identity/internal/core/issuer/verification:
    interfaces:
      Service: {}
  github.com/agntcy/identity/internal/core/vc:
    interfaces:
      Repository: {}
  github.com/agntcy/identity/pkg/oidc:
    interfaces:
      Parser:
          config:
            dir: 'internal/core/issuer/verification/mocks'
