// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/pkg/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

type Parser_Expecter struct {
	mock *mock.Mock
}

func (_m *Parser) EXPECT() *Parser_Expecter {
	return &Parser_Expecter{mock: &_m.Mock}
}

// ParseJwt provides a mock function for the type Parser
func (_mock *Parser) ParseJwt(ctx context.Context, jwtString *string) (*oidc.ParsedJWT, error) {
	ret := _mock.Called(ctx, jwtString)

	if len(ret) == 0 {
		panic("no return value specified for ParseJwt")
	}

	var r0 *oidc.ParsedJWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) (*oidc.ParsedJWT, error)); ok {
		return returnFunc(ctx, jwtString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) *oidc.ParsedJWT); ok {
		r0 = returnFunc(ctx, jwtString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oidc.ParsedJWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctx, jwtString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Parser_ParseJwt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseJwt'
type Parser_ParseJwt_Call struct {
	*mock.Call
}

// ParseJwt is a helper method to define mock.On call
//   - ctx context.Context
//   - jwtString *string
func (_e *Parser_Expecter) ParseJwt(ctx interface{}, jwtString interface{}) *Parser_ParseJwt_Call {
	return &Parser_ParseJwt_Call{Call: _e.mock.On("ParseJwt", ctx, jwtString)}
}

func (_c *Parser_ParseJwt_Call) Run(run func(ctx context.Context, jwtString *string)) *Parser_ParseJwt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_ParseJwt_Call) Return(parsedJWT *oidc.ParsedJWT, err error) *Parser_ParseJwt_Call {
	_c.Call.Return(parsedJWT, err)
	return _c
}

func (_c *Parser_ParseJwt_Call) RunAndReturn(run func(ctx context.Context, jwtString *string) (*oidc.ParsedJWT, error)) *Parser_ParseJwt_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyJwt provides a mock function for the type Parser
func (_mock *Parser) VerifyJwt(ctx context.Context, jwt *oidc.ParsedJWT) error {
	ret := _mock.Called(ctx, jwt)

	if len(ret) == 0 {
		panic("no return value specified for VerifyJwt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *oidc.ParsedJWT) error); ok {
		r0 = returnFunc(ctx, jwt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Parser_VerifyJwt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyJwt'
type Parser_VerifyJwt_Call struct {
	*mock.Call
}

// VerifyJwt is a helper method to define mock.On call
//   - ctx context.Context
//   - jwt *oidc.ParsedJWT
func (_e *Parser_Expecter) VerifyJwt(ctx interface{}, jwt interface{}) *Parser_VerifyJwt_Call {
	return &Parser_VerifyJwt_Call{Call: _e.mock.On("VerifyJwt", ctx, jwt)}
}

func (_c *Parser_VerifyJwt_Call) Run(run func(ctx context.Context, jwt *oidc.ParsedJWT)) *Parser_VerifyJwt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *oidc.ParsedJWT
		if args[1] != nil {
			arg1 = args[1].(*oidc.ParsedJWT)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Parser_VerifyJwt_Call) Return(err error) *Parser_VerifyJwt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Parser_VerifyJwt_Call) RunAndReturn(run func(ctx context.Context, jwt *oidc.ParsedJWT) error) *Parser_VerifyJwt_Call {
	_c.Call.Return(run)
	return _c
}
