// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/issuer/types"
	"github.com/agntcy/identity/internal/core/issuer/verification"
	types0 "github.com/agntcy/identity/internal/core/vc/types"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type Service
func (_mock *Service) Verify(ctx context.Context, issuer *types.Issuer, proof *types0.Proof) (*verification.Result, error) {
	ret := _mock.Called(ctx, issuer, proof)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *verification.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Issuer, *types0.Proof) (*verification.Result, error)); ok {
		return returnFunc(ctx, issuer, proof)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Issuer, *types0.Proof) *verification.Result); ok {
		r0 = returnFunc(ctx, issuer, proof)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*verification.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Issuer, *types0.Proof) error); ok {
		r1 = returnFunc(ctx, issuer, proof)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type Service_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer *types.Issuer
//   - proof *types0.Proof
func (_e *Service_Expecter) Verify(ctx interface{}, issuer interface{}, proof interface{}) *Service_Verify_Call {
	return &Service_Verify_Call{Call: _e.mock.On("Verify", ctx, issuer, proof)}
}

func (_c *Service_Verify_Call) Run(run func(ctx context.Context, issuer *types.Issuer, proof *types0.Proof)) *Service_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Issuer
		if args[1] != nil {
			arg1 = args[1].(*types.Issuer)
		}
		var arg2 *types0.Proof
		if args[2] != nil {
			arg2 = args[2].(*types0.Proof)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Verify_Call) Return(result *verification.Result, err error) *Service_Verify_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Service_Verify_Call) RunAndReturn(run func(ctx context.Context, issuer *types.Issuer, proof *types0.Proof) (*verification.Result, error)) *Service_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyExistingIssuer provides a mock function for the type Service
func (_mock *Service) VerifyExistingIssuer(ctx context.Context, proof *types0.Proof) (*verification.Result, error) {
	ret := _mock.Called(ctx, proof)

	if len(ret) == 0 {
		panic("no return value specified for VerifyExistingIssuer")
	}

	var r0 *verification.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types0.Proof) (*verification.Result, error)); ok {
		return returnFunc(ctx, proof)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types0.Proof) *verification.Result); ok {
		r0 = returnFunc(ctx, proof)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*verification.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types0.Proof) error); ok {
		r1 = returnFunc(ctx, proof)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_VerifyExistingIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyExistingIssuer'
type Service_VerifyExistingIssuer_Call struct {
	*mock.Call
}

// VerifyExistingIssuer is a helper method to define mock.On call
//   - ctx context.Context
//   - proof *types0.Proof
func (_e *Service_Expecter) VerifyExistingIssuer(ctx interface{}, proof interface{}) *Service_VerifyExistingIssuer_Call {
	return &Service_VerifyExistingIssuer_Call{Call: _e.mock.On("VerifyExistingIssuer", ctx, proof)}
}

func (_c *Service_VerifyExistingIssuer_Call) Run(run func(ctx context.Context, proof *types0.Proof)) *Service_VerifyExistingIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types0.Proof
		if args[1] != nil {
			arg1 = args[1].(*types0.Proof)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_VerifyExistingIssuer_Call) Return(result *verification.Result, err error) *Service_VerifyExistingIssuer_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Service_VerifyExistingIssuer_Call) RunAndReturn(run func(ctx context.Context, proof *types0.Proof) (*verification.Result, error)) *Service_VerifyExistingIssuer_Call {
	_c.Call.Return(run)
	return _c
}
