FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c AS builder

# Build the package
WORKDIR /build
COPY . .
RUN go mod download
RUN cd ./cmd/node && go build -o ../../identity-node

RUN apk update \
    &&  apk add ca-certificates wget \
    &&  update-ca-certificates

FROM golang:1.26.8-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c

# Create a group and user
RUN addgroup -S web && adduser -u 1999 -S -G web web

# Set workdir
WORKDIR /home/web

COPY --from=builder /build/identity-node .

# Give permissions
RUN chmod +x identity-node && \
    chown -R web:web .

USER web

ENTRYPOINT ["./identity-node"]
