// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/issuer/types"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateIssuer provides a mock function for the type Repository
func (_mock *Repository) CreateIssuer(ctx context.Context, issuer *types.Issuer) (*types.Issuer, error) {
	ret := _mock.Called(ctx, issuer)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssuer")
	}

	var r0 *types.Issuer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Issuer) (*types.Issuer, error)); ok {
		return returnFunc(ctx, issuer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Issuer) *types.Issuer); ok {
		r0 = returnFunc(ctx, issuer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Issuer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Issuer) error); ok {
		r1 = returnFunc(ctx, issuer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CreateIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssuer'
type Repository_CreateIssuer_Call struct {
	*mock.Call
}

// CreateIssuer is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer *types.Issuer
func (_e *Repository_Expecter) CreateIssuer(ctx interface{}, issuer interface{}) *Repository_CreateIssuer_Call {
	return &Repository_CreateIssuer_Call{Call: _e.mock.On("CreateIssuer", ctx, issuer)}
}

func (_c *Repository_CreateIssuer_Call) Run(run func(ctx context.Context, issuer *types.Issuer)) *Repository_CreateIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Issuer
		if args[1] != nil {
			arg1 = args[1].(*types.Issuer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CreateIssuer_Call) Return(issuer1 *types.Issuer, err error) *Repository_CreateIssuer_Call {
	_c.Call.Return(issuer1, err)
	return _c
}

func (_c *Repository_CreateIssuer_Call) RunAndReturn(run func(ctx context.Context, issuer *types.Issuer) (*types.Issuer, error)) *Repository_CreateIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuer provides a mock function for the type Repository
func (_mock *Repository) GetIssuer(ctx context.Context, commonName string) (*types.Issuer, error) {
	ret := _mock.Called(ctx, commonName)

	if len(ret) == 0 {
		panic("no return value specified for GetIssuer")
	}

	var r0 *types.Issuer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Issuer, error)); ok {
		return returnFunc(ctx, commonName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Issuer); ok {
		r0 = returnFunc(ctx, commonName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Issuer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, commonName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuer'
type Repository_GetIssuer_Call struct {
	*mock.Call
}

// GetIssuer is a helper method to define mock.On call
//   - ctx context.Context
//   - commonName string
func (_e *Repository_Expecter) GetIssuer(ctx interface{}, commonName interface{}) *Repository_GetIssuer_Call {
	return &Repository_GetIssuer_Call{Call: _e.mock.On("GetIssuer", ctx, commonName)}
}

func (_c *Repository_GetIssuer_Call) Run(run func(ctx context.Context, commonName string)) *Repository_GetIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetIssuer_Call) Return(issuer *types.Issuer, err error) *Repository_GetIssuer_Call {
	_c.Call.Return(issuer, err)
	return _c
}

func (_c *Repository_GetIssuer_Call) RunAndReturn(run func(ctx context.Context, commonName string) (*types.Issuer, error)) *Repository_GetIssuer_Call {
	_c.Call.Return(run)
	return _c
}
