# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: identity-node
version: 0.1.3
appVersion: "0.0.2"
description: A Helm chart for deploying an Identity Node with a PostgreSQL instance.
type: application
maintainers:
  - name: identity
    url: https://github.com/agntcy/identity
sources:
  - https://github.com/agntcy/identity
dependencies:
  - name: postgresql
    version: 16.7.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
