# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: identity-node
services:
  identity-api:
    container_name: identity-node
    build:
      context: ../../../
      dockerfile: deployments/docker/identity/Dockerfile.node
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
    env_file:
      - .env
    networks:
      - identity-network

networks:
  identity-network:
    external: true
