# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: identity-couchdb
services:
  couchdb:
    image: couchdb:latest
    container_name: identity-couchdb
    restart: always
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    ports:
      - "5984:5984"
    env_file:
      - .env
    networks:
      - identity-network

volumes:
  couchdb-data:

networks:
  identity-network:
    external: true
