# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  APP_ENV: {{ .Values.config.appEnv | default "production" | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}
  {{- range $key, $value := .Values.config.extraConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
data:
  APP_ENV: "production"
  DATABASE_URL: "postgresql://user:password@postgresql-service:5432/mydatabase"
  LOG_LEVEL: "info"