# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-node.fullname" . }}-config
  labels:
    {{ include "identity-node.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | default "production" | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"