# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | default "postgres" | b64enc | quote }}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}