# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: identity-node
version: 0.1.0
appVersion: "1.0.0"
description: A Helm chart for deploying identity node with PostgreSQL instance.
type: application
maintainers:
  - name: identity
    url: https://github.com/agntcy/identity
sources:
  - https://github.com/agntcy/identity
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami