name: pyramid-node
services:
  pyramid-api:
    container_name: pyramid-node
    build:
      context: ../../../
      dockerfile: deployments/docker/backend/node/Dockerfile
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
    env_file:
      - .env
    networks:
      - pyramid-network

networks:
  pyramid-network:
    external: true
