// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	types0 "github.com/agntcy/identity/internal/core/issuer/types"
	"github.com/agntcy/identity/internal/core/vc/types"
	mock "github.com/stretchr/testify/mock"
)

// NewIDGenerator creates a new instance of IDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDGenerator {
	mock := &IDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IDGenerator is an autogenerated mock type for the IDGenerator type
type IDGenerator struct {
	mock.Mock
}

type IDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *IDGenerator) EXPECT() *IDGenerator_Expecter {
	return &IDGenerator_Expecter{mock: &_m.Mock}
}

// GenerateFromProof provides a mock function for the type IDGenerator
func (_mock *IDGenerator) GenerateFromProof(ctx context.Context, proof *types.Proof) (string, *types0.Issuer, error) {
	ret := _mock.Called(ctx, proof)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromProof")
	}

	var r0 string
	var r1 *types0.Issuer
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Proof) (string, *types0.Issuer, error)); ok {
		return returnFunc(ctx, proof)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Proof) string); ok {
		r0 = returnFunc(ctx, proof)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.Proof) *types0.Issuer); ok {
		r1 = returnFunc(ctx, proof)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types0.Issuer)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *types.Proof) error); ok {
		r2 = returnFunc(ctx, proof)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IDGenerator_GenerateFromProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromProof'
type IDGenerator_GenerateFromProof_Call struct {
	*mock.Call
}

// GenerateFromProof is a helper method to define mock.On call
//   - ctx context.Context
//   - proof *types.Proof
func (_e *IDGenerator_Expecter) GenerateFromProof(ctx interface{}, proof interface{}) *IDGenerator_GenerateFromProof_Call {
	return &IDGenerator_GenerateFromProof_Call{Call: _e.mock.On("GenerateFromProof", ctx, proof)}
}

func (_c *IDGenerator_GenerateFromProof_Call) Run(run func(ctx context.Context, proof *types.Proof)) *IDGenerator_GenerateFromProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Proof
		if args[1] != nil {
			arg1 = args[1].(*types.Proof)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IDGenerator_GenerateFromProof_Call) Return(s string, issuer *types0.Issuer, err error) *IDGenerator_GenerateFromProof_Call {
	_c.Call.Return(s, issuer, err)
	return _c
}

func (_c *IDGenerator_GenerateFromProof_Call) RunAndReturn(run func(ctx context.Context, proof *types.Proof) (string, *types0.Issuer, error)) *IDGenerator_GenerateFromProof_Call {
	_c.Call.Return(run)
	return _c
}
