// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/issuer/types"
	types0 "github.com/agntcy/identity/internal/core/vc/types"
	"github.com/agntcy/identity/pkg/jwk"
	mock "github.com/stretchr/testify/mock"
)

// NewIssuerService creates a new instance of IssuerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssuerService {
	mock := &IssuerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IssuerService is an autogenerated mock type for the IssuerService type
type IssuerService struct {
	mock.Mock
}

type IssuerService_Expecter struct {
	mock *mock.Mock
}

func (_m *IssuerService) EXPECT() *IssuerService_Expecter {
	return &IssuerService_Expecter{mock: &_m.Mock}
}

// GetJwks provides a mock function for the type IssuerService
func (_mock *IssuerService) GetJwks(ctx context.Context, commonName string) (*jwk.Jwks, error) {
	ret := _mock.Called(ctx, commonName)

	if len(ret) == 0 {
		panic("no return value specified for GetJwks")
	}

	var r0 *jwk.Jwks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwk.Jwks, error)); ok {
		return returnFunc(ctx, commonName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwk.Jwks); ok {
		r0 = returnFunc(ctx, commonName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwk.Jwks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, commonName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IssuerService_GetJwks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJwks'
type IssuerService_GetJwks_Call struct {
	*mock.Call
}

// GetJwks is a helper method to define mock.On call
//   - ctx context.Context
//   - commonName string
func (_e *IssuerService_Expecter) GetJwks(ctx interface{}, commonName interface{}) *IssuerService_GetJwks_Call {
	return &IssuerService_GetJwks_Call{Call: _e.mock.On("GetJwks", ctx, commonName)}
}

func (_c *IssuerService_GetJwks_Call) Run(run func(ctx context.Context, commonName string)) *IssuerService_GetJwks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IssuerService_GetJwks_Call) Return(jwks *jwk.Jwks, err error) *IssuerService_GetJwks_Call {
	_c.Call.Return(jwks, err)
	return _c
}

func (_c *IssuerService_GetJwks_Call) RunAndReturn(run func(ctx context.Context, commonName string) (*jwk.Jwks, error)) *IssuerService_GetJwks_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type IssuerService
func (_mock *IssuerService) Register(ctx context.Context, issuer *types.Issuer, proof *types0.Proof) error {
	ret := _mock.Called(ctx, issuer, proof)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Issuer, *types0.Proof) error); ok {
		r0 = returnFunc(ctx, issuer, proof)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IssuerService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IssuerService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer *types.Issuer
//   - proof *types0.Proof
func (_e *IssuerService_Expecter) Register(ctx interface{}, issuer interface{}, proof interface{}) *IssuerService_Register_Call {
	return &IssuerService_Register_Call{Call: _e.mock.On("Register", ctx, issuer, proof)}
}

func (_c *IssuerService_Register_Call) Run(run func(ctx context.Context, issuer *types.Issuer, proof *types0.Proof)) *IssuerService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Issuer
		if args[1] != nil {
			arg1 = args[1].(*types.Issuer)
		}
		var arg2 *types0.Proof
		if args[2] != nil {
			arg2 = args[2].(*types0.Proof)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IssuerService_Register_Call) Return(err error) *IssuerService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IssuerService_Register_Call) RunAndReturn(run func(ctx context.Context, issuer *types.Issuer, proof *types0.Proof) error) *IssuerService_Register_Call {
	_c.Call.Return(run)
	return _c
}
