// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/vc/types"
	mock "github.com/stretchr/testify/mock"
)

// NewVerifiableCredentialService creates a new instance of VerifiableCredentialService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifiableCredentialService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerifiableCredentialService {
	mock := &VerifiableCredentialService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VerifiableCredentialService is an autogenerated mock type for the VerifiableCredentialService type
type VerifiableCredentialService struct {
	mock.Mock
}

type VerifiableCredentialService_Expecter struct {
	mock *mock.Mock
}

func (_m *VerifiableCredentialService) EXPECT() *VerifiableCredentialService_Expecter {
	return &VerifiableCredentialService_Expecter{mock: &_m.Mock}
}

// GetVcs provides a mock function for the type VerifiableCredentialService
func (_mock *VerifiableCredentialService) GetVcs(ctx context.Context, resolverMetadataID string) ([]*types.EnvelopedCredential, error) {
	ret := _mock.Called(ctx, resolverMetadataID)

	if len(ret) == 0 {
		panic("no return value specified for GetVcs")
	}

	var r0 []*types.EnvelopedCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*types.EnvelopedCredential, error)); ok {
		return returnFunc(ctx, resolverMetadataID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*types.EnvelopedCredential); ok {
		r0 = returnFunc(ctx, resolverMetadataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.EnvelopedCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, resolverMetadataID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerifiableCredentialService_GetVcs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVcs'
type VerifiableCredentialService_GetVcs_Call struct {
	*mock.Call
}

// GetVcs is a helper method to define mock.On call
//   - ctx context.Context
//   - resolverMetadataID string
func (_e *VerifiableCredentialService_Expecter) GetVcs(ctx interface{}, resolverMetadataID interface{}) *VerifiableCredentialService_GetVcs_Call {
	return &VerifiableCredentialService_GetVcs_Call{Call: _e.mock.On("GetVcs", ctx, resolverMetadataID)}
}

func (_c *VerifiableCredentialService_GetVcs_Call) Run(run func(ctx context.Context, resolverMetadataID string)) *VerifiableCredentialService_GetVcs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VerifiableCredentialService_GetVcs_Call) Return(envelopedCredentials []*types.EnvelopedCredential, err error) *VerifiableCredentialService_GetVcs_Call {
	_c.Call.Return(envelopedCredentials, err)
	return _c
}

func (_c *VerifiableCredentialService_GetVcs_Call) RunAndReturn(run func(ctx context.Context, resolverMetadataID string) ([]*types.EnvelopedCredential, error)) *VerifiableCredentialService_GetVcs_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type VerifiableCredentialService
func (_mock *VerifiableCredentialService) Publish(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof) error {
	ret := _mock.Called(ctx, credential, proof)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.EnvelopedCredential, *types.Proof) error); ok {
		r0 = returnFunc(ctx, credential, proof)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VerifiableCredentialService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type VerifiableCredentialService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *types.EnvelopedCredential
//   - proof *types.Proof
func (_e *VerifiableCredentialService_Expecter) Publish(ctx interface{}, credential interface{}, proof interface{}) *VerifiableCredentialService_Publish_Call {
	return &VerifiableCredentialService_Publish_Call{Call: _e.mock.On("Publish", ctx, credential, proof)}
}

func (_c *VerifiableCredentialService_Publish_Call) Run(run func(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof)) *VerifiableCredentialService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.EnvelopedCredential
		if args[1] != nil {
			arg1 = args[1].(*types.EnvelopedCredential)
		}
		var arg2 *types.Proof
		if args[2] != nil {
			arg2 = args[2].(*types.Proof)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerifiableCredentialService_Publish_Call) Return(err error) *VerifiableCredentialService_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VerifiableCredentialService_Publish_Call) RunAndReturn(run func(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof) error) *VerifiableCredentialService_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type VerifiableCredentialService
func (_mock *VerifiableCredentialService) Revoke(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof) error {
	ret := _mock.Called(ctx, credential, proof)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.EnvelopedCredential, *types.Proof) error); ok {
		r0 = returnFunc(ctx, credential, proof)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VerifiableCredentialService_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type VerifiableCredentialService_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *types.EnvelopedCredential
//   - proof *types.Proof
func (_e *VerifiableCredentialService_Expecter) Revoke(ctx interface{}, credential interface{}, proof interface{}) *VerifiableCredentialService_Revoke_Call {
	return &VerifiableCredentialService_Revoke_Call{Call: _e.mock.On("Revoke", ctx, credential, proof)}
}

func (_c *VerifiableCredentialService_Revoke_Call) Run(run func(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof)) *VerifiableCredentialService_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.EnvelopedCredential
		if args[1] != nil {
			arg1 = args[1].(*types.EnvelopedCredential)
		}
		var arg2 *types.Proof
		if args[2] != nil {
			arg2 = args[2].(*types.Proof)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VerifiableCredentialService_Revoke_Call) Return(err error) *VerifiableCredentialService_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VerifiableCredentialService_Revoke_Call) RunAndReturn(run func(ctx context.Context, credential *types.EnvelopedCredential, proof *types.Proof) error) *VerifiableCredentialService_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type VerifiableCredentialService
func (_mock *VerifiableCredentialService) Verify(ctx context.Context, credential *types.EnvelopedCredential) (*types.VerificationResult, error) {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *types.VerificationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.EnvelopedCredential) (*types.VerificationResult, error)); ok {
		return returnFunc(ctx, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.EnvelopedCredential) *types.VerificationResult); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.VerificationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.EnvelopedCredential) error); ok {
		r1 = returnFunc(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VerifiableCredentialService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type VerifiableCredentialService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *types.EnvelopedCredential
func (_e *VerifiableCredentialService_Expecter) Verify(ctx interface{}, credential interface{}) *VerifiableCredentialService_Verify_Call {
	return &VerifiableCredentialService_Verify_Call{Call: _e.mock.On("Verify", ctx, credential)}
}

func (_c *VerifiableCredentialService_Verify_Call) Run(run func(ctx context.Context, credential *types.EnvelopedCredential)) *VerifiableCredentialService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.EnvelopedCredential
		if args[1] != nil {
			arg1 = args[1].(*types.EnvelopedCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VerifiableCredentialService_Verify_Call) Return(verificationResult *types.VerificationResult, err error) *VerifiableCredentialService_Verify_Call {
	_c.Call.Return(verificationResult, err)
	return _c
}

func (_c *VerifiableCredentialService_Verify_Call) RunAndReturn(run func(ctx context.Context, credential *types.EnvelopedCredential) (*types.VerificationResult, error)) *VerifiableCredentialService_Verify_Call {
	_c.Call.Return(run)
	return _c
}
