---
linters-settings:
  cyclop:
    max-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - unnamedResult
  govet:
    disable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    severity: warning
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-anything: true
    force-err-cuddling: true
    force-short-decl-cuddling: false
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - govet
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

  exclusions:
    paths:
      - '.*_test\.go'
      - '.*\.pb\.go'
      - '.*\.gen\.go'
      - '.*\.pb\.gw\.go'
      - '.*\.mock\.go'
      - '.*\.generated\.go'
      - '.*_gen\.go'
      - '.*_testdata\.go'
      - '.*_testdata/.*'
      - '.*_test/.*'
      - '.*_test.go/.*'
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
      - stylecheck
      text: "ST1003:"

    - linters:
      - stylecheck
      text: "ST1000:"


run:
  issues-exit-code: 1
  go: '1.24.1'
