// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/agntcy/identity/internal/core/id/types"
	types0 "github.com/agntcy/identity/internal/core/issuer/types"
	mock "github.com/stretchr/testify/mock"
)

// NewIdRepository creates a new instance of IdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdRepository {
	mock := &IdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdRepository is an autogenerated mock type for the IdRepository type
type IdRepository struct {
	mock.Mock
}

type IdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IdRepository) EXPECT() *IdRepository_Expecter {
	return &IdRepository_Expecter{mock: &_m.Mock}
}

// CreateID provides a mock function for the type IdRepository
func (_mock *IdRepository) CreateID(ctx context.Context, metadata *types.ResolverMetadata, issuer *types0.Issuer) (*types.ResolverMetadata, error) {
	ret := _mock.Called(ctx, metadata, issuer)

	if len(ret) == 0 {
		panic("no return value specified for CreateID")
	}

	var r0 *types.ResolverMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ResolverMetadata, *types0.Issuer) (*types.ResolverMetadata, error)); ok {
		return returnFunc(ctx, metadata, issuer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ResolverMetadata, *types0.Issuer) *types.ResolverMetadata); ok {
		r0 = returnFunc(ctx, metadata, issuer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ResolverMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *types.ResolverMetadata, *types0.Issuer) error); ok {
		r1 = returnFunc(ctx, metadata, issuer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdRepository_CreateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateID'
type IdRepository_CreateID_Call struct {
	*mock.Call
}

// CreateID is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *types.ResolverMetadata
//   - issuer *types0.Issuer
func (_e *IdRepository_Expecter) CreateID(ctx interface{}, metadata interface{}, issuer interface{}) *IdRepository_CreateID_Call {
	return &IdRepository_CreateID_Call{Call: _e.mock.On("CreateID", ctx, metadata, issuer)}
}

func (_c *IdRepository_CreateID_Call) Run(run func(ctx context.Context, metadata *types.ResolverMetadata, issuer *types0.Issuer)) *IdRepository_CreateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ResolverMetadata
		if args[1] != nil {
			arg1 = args[1].(*types.ResolverMetadata)
		}
		var arg2 *types0.Issuer
		if args[2] != nil {
			arg2 = args[2].(*types0.Issuer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IdRepository_CreateID_Call) Return(resolverMetadata *types.ResolverMetadata, err error) *IdRepository_CreateID_Call {
	_c.Call.Return(resolverMetadata, err)
	return _c
}

func (_c *IdRepository_CreateID_Call) RunAndReturn(run func(ctx context.Context, metadata *types.ResolverMetadata, issuer *types0.Issuer) (*types.ResolverMetadata, error)) *IdRepository_CreateID_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveID provides a mock function for the type IdRepository
func (_mock *IdRepository) ResolveID(ctx context.Context, id string) (*types.ResolverMetadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResolveID")
	}

	var r0 *types.ResolverMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.ResolverMetadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.ResolverMetadata); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ResolverMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdRepository_ResolveID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveID'
type IdRepository_ResolveID_Call struct {
	*mock.Call
}

// ResolveID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *IdRepository_Expecter) ResolveID(ctx interface{}, id interface{}) *IdRepository_ResolveID_Call {
	return &IdRepository_ResolveID_Call{Call: _e.mock.On("ResolveID", ctx, id)}
}

func (_c *IdRepository_ResolveID_Call) Run(run func(ctx context.Context, id string)) *IdRepository_ResolveID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdRepository_ResolveID_Call) Return(resolverMetadata *types.ResolverMetadata, err error) *IdRepository_ResolveID_Call {
	_c.Call.Return(resolverMetadata, err)
	return _c
}

func (_c *IdRepository_ResolveID_Call) RunAndReturn(run func(ctx context.Context, id string) (*types.ResolverMetadata, error)) *IdRepository_ResolveID_Call {
	_c.Call.Return(run)
	return _c
}
