# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Release the Issuer CLI and the Node Docker Image

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  pre-release-test:
    uses: cisco-eti/pyramid/.github/workflows/reusable-test.yml@main
