# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Release the Issuer CLI and the Node Docker Image

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - story/PYRA-148-build-and-push-the-docker-images-on-ci
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  pre-release-test:
    name: Pre Release Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: "echo ok"
    # uses: ./.github/workflows/reusable-test.yml

  prepare-release:
    name: Prepare Release
    needs: [pre-release-test]
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.get-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Get version
        id: get-version
        run: |
          version="$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          workdir: ./deployments/docker
          target: default
        continue-on-error: true

  build-and-push-images:
    name: Build and Push Docker Images
    uses: ./.github/workflows/reusable-docker.yml
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-release.outputs.targets) }}
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-release.outputs.image-tag }}
    secrets:
      github-token: ${{ secrets.GHCR_TOKEN }}
