# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Release the Issuer CLI and the Node Docker Image

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - story/PYRA-148-build-and-push-the-docker-images-on-ci
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  pre-release-test:
    uses: ./.github/workflows/reusable-test.yml

  prepare-release:
    name: Prepare Release
    needs: [pre-release-test]
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.get-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          version="$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@v6
        with:
          workdir: ./deployments/docker
          target: ${{ steps.resolve.outputs.target }}
        continue-on-error: true

  build-and-push-images:
    uses: ./.github/workflows/reusable-docker.yml
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-build.outputs.image-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
