# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Release the Issuer CLI and the Node Docker Image

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
jobs:
  pre-release-test:
    name: Pre Release Test
    uses: ./.github/workflows/reusable-test.yml

  prepare-release:
    name: Prepare Release
    needs: [pre-release-test]
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      targets: ${{ steps.all-targets.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.0
        with:
          fetch-depth: 0

      - name: Set version
        id: set-version
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> "$GITHUB_OUTPUT"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          workdir: ./deployments/docker
          target: default
        continue-on-error: true

  build-and-push-all-images:
    name: Build and Push Docker Images
    uses: ./.github/workflows/reusable-docker.yml
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-release.outputs.targets) }}
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-release.outputs.version }}
      image-repo: ghcr.io/${{ github.repository }}
    secrets:
      github-token: ${{ secrets.GHCR_TOKEN }}

  build-and-release-issuer-client:
    name: Build and Release Issuer Cli
    uses: ./.github/workflows/reusable-go.yml
    needs: [prepare-release]
    with:
      workdir: ./identity/cmd/issuer
      config: ../../../.github/configs/issuer-cli-goreleaser.yml
    secrets:
      github-token: ${{ secrets.GHCR_TOKEN }}
