# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Reusable Python Build

on:
  workflow_call:
    py-version:
      description: 'Python version to install'
      required: false
      default: "3.12"
    uv-install:
      description: 'Install uv'
      required: false
      default: true

jobs:
  python-bindings-wheels:
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        shell: bash
        working-directory: ./sdk/python
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            os: linux
            target: x86_64
          - runner: windows-latest
            os: windows
            target: x64
          - runner: macos-13 # We use macos-13 as it is a x86_64 runner
            os: macos
            target: x86_64
          - runner: macos-15
            os: macos
            target: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        if: ${{ inputs.py-install }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.py-version }}
      - name: Build wheel
        run: |
          uv build
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: ./dist
      - name: Install uv (unix)
        if: ${{ inputs.uv-install && runner.os != 'Windows' }}
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${HOME}/.local/bin" sh
      - name: Install uv (windows)
        if: ${{ inputs.uv-install && runner.os == 'Windows' }}
        shell: bash
        run: |
          powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
      - name: Update GITHUB_PATH
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
